version: "3.8"

services:
  chatbot_server:
    build: .
    container_name: chatbot-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - chroma-server

  chroma-server:
    image: chromadb/chroma:latest
    container_name: chroma-server-3
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - chroma_data:/data
    environment:
      - CHROMA_SERVER_AUTH_CREDENTIALS=admin:admin
      - CHROMA_SERVER_AUTH_PROVIDER=chromadb.auth.token.TokenAuthServerProvider
      - CHROMA_SERVER_AUTH_TOKEN_TRANSPORT_HEADER=X-Chroma-Token

  nginx:
    image: nginx:alpine
    container_name: nginx_gateway
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - chatbot_server
      - chroma-server

volumes:
  chroma_data:
